apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp1
spec:
  containers:
    - name: nodeapp1
      image: raghu0708/nodeapp1:tagVersion
      ports:
        - containerPort: 8080
